version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: zerodha_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: zerodha
      POSTGRES_PASSWORD: zerodha123
      POSTGRES_DB: zerodha_mcp
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: zerodha_redis
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  pgdata:

